api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  title: saadbouh-website
  version: 1.0.0
  description: 'This is the API of saadbouh-website'

  defaults:
    pagination_enabled : false
    pagination_client_enabled : true
    pagination_client_items_per_page : true
  collection:
    pagination:
      page_parameter_name: page
      enabled_parameter_name: pagination
      items_per_page_parameter_name: itemsPerPage